services:
  drm-service:
    build: .
    image: drm-mgs-alpina:v1.0
    container_name: mgs-test
    ports:
      - "18080:18080"
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "pgrep -x /opt/mundfish/* > /dev/null || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: always

networks:
  drm-network:
    driver: bridge