version: '3.0'
services:
    su1-1zbx1:
        image: zabbix/zabbix-proxy-sqlite3:alpine-6.0-latest
        ports:
            - 10051:10051
        volumes:
            - /opt/mundfish/zabbix/docker-volumes/externalscripts:/usr/lib/zabbix/externalscripts:ro
            - /opt/mundfish/zabbix/docker-volumes/modules:/var/lib/zabbix/modules:ro
            - /opt/mundfish/zabbix/docker-volumes/enc:/var/lib/zabbix/enc:ro
            - /opt/mundfish/zabbix/docker-volumes/ssh_keys:/var/lib/zabbix/ssh_keys:ro
            - /opt/mundfish/zabbix/docker-volumes/ssl/certs:/var/lib/zabbix/ssl/certs:ro
            - /opt/mundfish/zabbix/docker-volumes/ssl/keys:/var/lib/zabbix/ssl/keys:ro
            - /opt/mundfish/zabbix/docker-volumes/ssl/ssl_ca:/var/lib/zabbix/ssl/ssl_ca:ro
            - /opt/mundfish/zabbix/docker-volumes/snmptraps:/var/lib/zabbix/snmptraps:ro
            - /opt/mundfish/zabbix/docker-volumes/mibs:/var/lib/zabbix/mibs:ro
        restart: always
        environment:
            - ZBX_HOSTNAME=su
            - ZBX_SERVER_HOST=de
            - ZBX_SERVER_PORT=10051
            - ZBX_DEBUGLEVEL=1
            - ZBX_PROXYMODE=0 # 0 - active proxy and 1 - passive proxy.
            - ZBX_CONFIGFREQUENCY=60
            - ZBX_TLSCONNECT=psk
#            - ZBX_TLSACCEPT=psk
            - ZBX_TLSPSKFILE=/run/secrets/zabbix-proxy-psk
            - ZBX_TLSPSKIDENTITY=su
        secrets:
            - zabbix-proxy-psk


    agent:
        image: zabbix/zabbix-agent:alpine-6.0-latest
        ports:
            - "10050:10050"
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /etc/timezone:/etc/timezone:ro
            - /proc:/proc
            - /sys:/sys
            - /dev:/dev
            - /var/run/docker.sock:/var/run/docker.sock
        privileged: true
        pid: "host"
        restart: always
        depends_on:
            - su
        environment:
            - ZBX_SERVER_HOST=su
            - ZBX_DEBUGLEVEL=1

secrets:
  zabbix-proxy-psk:
    file: ./zabbix-proxy.psk